### ISSUE TITLE
The Intercom API request failed with the code: 410, after 3 attempts.

### ISSUE THREAD

**Issue by raelgc** [intercom/intercom-rails#203] opened 2016-06-17 23:53 UTC
## Version info
  - intercom-rails version: 0.2.35
  - Rails version: 4.1.14.2

## Expected behavior

After run an import, all data is exported to Intercom.

## Actual behavior

Without any code changes from our side, we started to receive this message: `The Intercom API request failed with the code: 410, after 3 attempts`.

This message is not describe in Intercom documentation (while a `HTTP 410` does it means that the resource requested is no longer available and will not be available again, i.e, it was intentionally removed).

## Steps to reproduce
 1. We're using a Worker with this method to import data:

```ruby
  def self.run_import(options)
    collection = options[:collection]
    intercom = IntercomRails::Import.new(options)
    intercom.collection = collection
    intercom.run_import(collection)
  end
```

## Logs
```
The Intercom API request failed with the code: 410, after 3 attempts.
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:142:in `perform_request'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:148:in `perform_request'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:148:in `perform_request'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:148:in `perform_request'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:132:in `send_users'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:64:in `block in run'
/var/my_project/releases/2016-06-13_13_25_52/config/initializers/intercom_extension.rb:49:in `block in batches'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.14.2/lib/active_record/relation/batches.rb:126:in `find_in_batches'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/relation.rb:70:in `find_in_batches'
/var/my_project/releases/2016-06-13_13_25_52/config/initializers/intercom_extension.rb:47:in `batches'
/var/my_project/releases/2016-06-13_13_25_52/vendor/bundle/ruby/2.1.0/gems/intercom-rails-0.2.29/lib/intercom-rails/import.rb:63:in `run'
/var/my_project/releases/2016-06-13_13_25_52/config/initializers/intercom_extension.rb:22:in `run_import'
/var/my_project/releases/2016-06-13_13_25_52/config/initializers/intercom_extension.rb:17:in `run_import'
/var/my_project/releases/2016-06-13_13_25_52/app/workers/intercom_worker.rb:8:in `perform'
```

**Comment by bobjflong** [comment] 2016-06-18 13:37
Duplicate of https://github.com/intercom/intercom-rails/issues/202

Hi @raelgc 

This endpoint is deprecated and the importer will be removed from this gem in the next version. Please use the (much more effective) bulk endpoint: https://developers.intercom.io/reference#bulk-user-operations

This is wrapped in [intercom-ruby](https://github.com/intercom/intercom-ruby#users) if you need it.

Thanks,
Bob

**Closed by bobjflong** 2016-06-18 13:37 UTC

**Comment by raelgc** [comment] 2016-06-18 18:26
Thank you for the quick answer, @bobjflong!
